# Generated by Django 6.0.1 on 2026-03-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_loanapplication_credited_to_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='current_job',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
