# Generated by Django 6.0.1 on 2026-03-15 08:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_add_current_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='current_job',
        ),
        migrations.AddField(
            model_name='user',
            name='dashboard_status_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='is_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='off_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='interest_rate_monthly',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000500'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000000.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('80000.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default='89745', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
