# Generated by Django 6.0.1 on 2026-03-15 08:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_loanapplication_current_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dashboard_status_label',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_control',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_view',
        ),
        migrations.RemoveField(
            model_name='user',
            name='off_reason',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='current_job',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='interest_rate_monthly',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000300'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('60000000.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.PositiveIntegerField(default=650),
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
