# Generated by Django 6.0.1 on 2026-04-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_user_custom_status_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='current_living',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='guarantor_contact',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='guarantor_current_living',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='hometown',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='identity_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='identity_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='income',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_expenses',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
